int * GetMemory(int * length=NULL);
void fillArray(int *mass, int length);
void fillMatrix(int *mass, int length, int row);
void printArray(int *mass, int length);
void printMatrix(int *mass, int length, int row);
void SearchMax(int *mass, int *mass1, int length, int row);
void SearchMin(int *mass1, int length);
void ReversNumber(int *mass, int *mass1, int length);
int SearchSecondPositivElement(int *mass, int length);
void ReverseElements(int *mas, int length);
void ElementNeKrat3(int *mass, int length);
void SwitchMinAndLastElement(int *mass, int length);
long int TwoTo8(int *mass);
void ChetOrNechet(int *mas, int length);
void NotBiggerThan10(int *mas, int length);
void ArifmProgres(int *mass1, int length);
void Neighbor(int *mass, int length);
void SortOpredStolbca(int *mass, int column, int row);
void Pure(int *mass, int column, int row);